# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12U2Kus7x1rqBoFMbHpM86ZjnPQL22FTt
"""

def Reverse(lst):
    return [ele for ele in reversed(lst)]
      
# Driver Code
lst = [10, 11, 12, 13, 14, 15]
print(Reverse(lst))